<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo (http://leoeditor.com/leo_toc.html) -->
<?xml-stylesheet ekr_test?>
<leo_file xmlns:leo="http://www.leo-editor.org/2011/leo" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="2014python.20150323084742.1697"><vh>NewHeadline</vh></v>
<v t="2014python.20150323084742.1698" a="E"><vh>@path /</vh>
<v t="2014python.20150323084742.1699"><vh>@edit  SUMMARY.md</vh></v>
<v t="2014python.20150323084742.1701"><vh>@edit ch2.md</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="2014python.20150323084742.1697"></t>
<t tx="2014python.20150323084742.1698"></t>
</tnodes>
</leo_file>
